# Generated by Django 5.2.7 on 2025-10-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_path', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quant_dias', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('tipo_inscricao', models.CharField(blank=True, max_length=13, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('optante_simp_nacional', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(max_length=70, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadastro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=100)),
                ('data_matricula', models.DateField()),
                ('aula_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(blank=True, default=False, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('aula_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.aula')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.aluno')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.curso')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.turma'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.turma'),
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.aluno')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.turma')),
            ],
        ),
    ]
