# Generated by Django 5.2.7 on 2025-10-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_aluno_id_alter_aula_id_alter_curso_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='aula_id',
            new_name='aluno_id',
        ),
    ]
