# Generated by Django 5.2.7 on 2025-10-25 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_rename_aula_id_matricula_aluno_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='turma_id',
        ),
        migrations.CreateModel(
            name='TurmaAula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aula_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.aula')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastro.turma')),
            ],
        ),
    ]
