# Generated by Django 5.2.7 on 2025-10-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_aula_turma_id_turmaaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmaaluno',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aluno'),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma'),
        ),
        migrations.AlterField(
            model_name='turmaaula',
            name='aula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aula'),
        ),
        migrations.AlterField(
            model_name='turmaaula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma'),
        ),
    ]
