# Generated by Django 5.2.7 on 2025-10-25 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_turmaaluno_aluno_id_alter_turmaaluno_turma_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma'),
        ),
    ]
