# Generated by Django 5.2.7 on 2025-10-25 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_matricula_turma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='aula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aula'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='matricula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.matricula'),
        ),
    ]
