# Generated by Django 5.2.7 on 2025-10-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_frequencia_aula_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurmaAluno',
        ),
    ]
