# Generated by Django 5.2.7 on 2025-10-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_delete_turmaaluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurmaAula',
        ),
    ]
