# Generated by Django 5.2.7 on 2025-10-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_delete_turmaaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(default='Pix', max_length=50),
        ),
    ]
